CREATE TABLE IF NOT EXISTS operators (
 code VARCHAR(16) PRIMARY KEY, name VARCHAR(160) NOT NULL, contact VARCHAR(255) NOT NULL DEFAULT '',
 active TINYINT NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS agencies (
 code VARCHAR(32) PRIMARY KEY, name VARCHAR(160) NOT NULL, issuer_code CHAR(3) NOT NULL UNIQUE,
 contact VARCHAR(255) NOT NULL DEFAULT '', active TINYINT NOT NULL DEFAULT 1,
 api_key_hash CHAR(64) NULL UNIQUE, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS agency_operators (
 agency_code VARCHAR(32) NOT NULL, operator_code VARCHAR(16) NOT NULL,
 PRIMARY KEY(agency_code,operator_code), FOREIGN KEY(agency_code) REFERENCES agencies(code),
 FOREIGN KEY(operator_code) REFERENCES operators(code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
