CREATE TABLE IF NOT EXISTS imports (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 dimension VARCHAR(160) NOT NULL, service_date DATE NOT NULL, source_hash CHAR(64) NOT NULL,
 report LONGTEXT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS stations (
 id VARCHAR(160) PRIMARY KEY, mtr_id VARCHAR(20) NOT NULL, dimension VARCHAR(120) NOT NULL,
 name VARCHAR(512) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS trips (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, import_id BIGINT UNSIGNED NOT NULL,
 dimension VARCHAR(120) NOT NULL, service_date DATE NOT NULL, trip_key CHAR(64) NOT NULL,
 operator_code VARCHAR(16) NOT NULL, name VARCHAR(512) NOT NULL,
 depot_id VARCHAR(20) NOT NULL, siding_id VARCHAR(20) NOT NULL, run_number INT UNSIGNED NULL, route_ids TEXT NOT NULL,
 capacity INT UNSIGNED NOT NULL, fare_per_segment INT UNSIGNED NOT NULL, active TINYINT NOT NULL DEFAULT 1,
 INDEX journey_date(service_date,active), FOREIGN KEY(import_id) REFERENCES imports(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS stops (
 trip_id BIGINT UNSIGNED NOT NULL, seq INT UNSIGNED NOT NULL,
 station_id VARCHAR(160) NOT NULL, platform_id VARCHAR(20) NOT NULL,
 arrival_at DATETIME(3) NOT NULL, departure_at DATETIME(3) NOT NULL,
 PRIMARY KEY(trip_id,seq), INDEX search_station(station_id,departure_at),
 FOREIGN KEY(trip_id) REFERENCES trips(id), FOREIGN KEY(station_id) REFERENCES stations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS tickets (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, ticket_number CHAR(13) NOT NULL UNIQUE,
 pnr CHAR(6) NOT NULL UNIQUE, issuer_code CHAR(3) NOT NULL, agency_code VARCHAR(32) NOT NULL,
 passenger VARCHAR(160) NOT NULL, amount_minor INT UNSIGNED NOT NULL, currency CHAR(3) NOT NULL,
 status ENUM('OPEN','RFND') NOT NULL DEFAULT 'OPEN', issued_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 refunded_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS coupons (
 ticket_id BIGINT UNSIGNED NOT NULL, number INT UNSIGNED NOT NULL DEFAULT 1,
 trip_id BIGINT UNSIGNED NOT NULL, origin_seq INT UNSIGNED NOT NULL, destination_seq INT UNSIGNED NOT NULL,
 status ENUM('OPEN','RFND') NOT NULL DEFAULT 'OPEN', PRIMARY KEY(ticket_id,number),
 INDEX occupancy(trip_id,status,origin_seq,destination_seq),
 FOREIGN KEY(ticket_id) REFERENCES tickets(id), FOREIGN KEY(trip_id) REFERENCES trips(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS requests (
 agency_code VARCHAR(32) NOT NULL, request_key VARCHAR(100) NOT NULL, body_hash CHAR(64) NOT NULL,
 ticket_id BIGINT UNSIGNED NOT NULL, PRIMARY KEY(agency_code,request_key),
 FOREIGN KEY(ticket_id) REFERENCES tickets(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS ticket_events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, ticket_id BIGINT UNSIGNED NOT NULL,
 agency_code VARCHAR(32) NOT NULL, action VARCHAR(20) NOT NULL, occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(ticket_id) REFERENCES tickets(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

