CREATE TABLE IF NOT EXISTS ticket_tlv (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 ticket_id BIGINT UNSIGNED NOT NULL, operator_code VARCHAR(16) NOT NULL,
 tag INT UNSIGNED NOT NULL, byte_length INT UNSIGNED NOT NULL,
 encoding VARCHAR(8) NOT NULL, value_base64 MEDIUMTEXT NOT NULL, label VARCHAR(160) NOT NULL DEFAULT '',
 actor_role VARCHAR(16) NOT NULL, actor_code VARCHAR(32) NOT NULL,
 created_at DATETIME(3) NOT NULL, revoked_at DATETIME(3) NULL,
 INDEX ticket_operator(ticket_id,operator_code,id),
 FOREIGN KEY(ticket_id) REFERENCES tickets(id) ON DELETE CASCADE,
 FOREIGN KEY(operator_code) REFERENCES operators(code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS ticket_tlv_events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tlv_id BIGINT UNSIGNED NOT NULL,
 action VARCHAR(16) NOT NULL, actor_role VARCHAR(16) NOT NULL, actor_code VARCHAR(32) NOT NULL,
 reason VARCHAR(500) NOT NULL, occurred_at DATETIME(3) NOT NULL,
 FOREIGN KEY(tlv_id) REFERENCES ticket_tlv(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
